name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  TEAMS_WEBHOOK_URL: ''
  CI: false
  
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test tests/api.spec.ts
    - name: Suppress GitHub Annotations
      run: sed -i '/::error\|::warning\|::notice/d' test-output.log
    ########################################
    # Publish CTRF Test Summary Results
    ########################################
    - name: Publish CTRF Test Summary Results
      run: |
       npx github-actions-ctrf suite-folded ctrf/ctrf-report.json
       npx github-actions-ctrf summary path-to-your-ctrf-report.json
      if: always()
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
  ############################################
    # Publish CTRF Results in Teams Channel
  ########################################
    # - name: set webhook url 
    #   run : export env.TEAMS_WEBHOOK_URL= ${{ secrets.TEAMS_WEBHOOK_URL }}
    # - name: Publish CTRF Test Summary Results in Teams Channel
    #   run : npx teams-ctrf results ctrf/ctrf-report.json
    #   if: always()
