name: Playwright Tests
on:
  workflow_dispatch:

# env:
#   TEAMS_WEBHOOK_URL: ''
#   CI_OVERRIDE: true
  
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: |
           npx playwright test tests/api.spec.ts
        # npx playwright test tests/api.spec.ts > filtered-output.log 2>&1
        # sed -i '/::error\|::warning\|::notice/d' filtered-output.log
        # cat filtered-output.log
    ########################################
    # Publish CTRF Test Summary Results
    ########################################
    # - name: Publish CTRF Test Summary Results
    #   run: |
    #    npx github-actions-ctrf suite-folded ctrf/ctrf-report.json
    #    npx github-actions-ctrf summary ctrf/ctrf-report.json
    #   if: always()
    # - uses: actions/upload-artifact@v4
    #   if: ${{ !cancelled() }}
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30
  ############################################
    # Publish CTRF Results in Teams Channel
  ########################################
    # - name: set webhook url 
    #   run : export env.TEAMS_WEBHOOK_URL= ${{ secrets.TEAMS_WEBHOOK_URL }}
    # - name: Publish CTRF Test Summary Results in Teams Channel
    #   run : npx teams-ctrf results ctrf/ctrf-report.json
    #   if: always()

  ############################################
    # Publish CTRF Results in Teams Channel
  ########################################
    - name: Read Summary Report to Get Test Results
      if: always()
      run: |
        STATUS=$(cat ./summary.json | jq -r '.status')
        echo "STATUS=$STATUS" >> $GITHUB_ENV 
        PASSED=$(cat ./summary.json | jq -r '.passed[]' | tr '\n' ' ')
        echo "PASSED=$PASSED" >> $GITHUB_ENV 
        TIMEOUT=$(cat ./summary.json | jq -r '.timedOut[]' | tr '\n' ' ' | sed 's/ /--->TIMEOUT /g')
        FAILURES=$(cat ./summary.json | jq -r '.failed[]' | tr '\n' ' ')
        FAILURES+=$TIMEOUT
        echo "FAILURES=$FAILURES" >> $GITHUB_ENV
...
